In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import random

from sklearn.linear_model import LogisticRegression

In [11]:
age_classifier = pd.DataFrame([[range(18, 22), 2],
                                [range(22, 26), 3],
                                [range(26, 31), 4],
                                [range(31, 37), 5],
                                [range(37, 46), 5],
                                [range(46, 56), 4],
                                [range(56, 66), 2]], 
                                columns = ['Age', 'Mark'])
apptype_classifier = pd.DataFrame([['Card', 0],
                                   ['Consumer loan', 1],
                                   ['Car loan', 2],
                                   ['Mortgage', 3],
                                   ['SP loan', 1]], 
                                    columns = ['AppType', 'Mark'])
edu_classifier = pd.DataFrame([['Secondary', 0],
                               ['High school', 1],
                               ['Sharaga', 2],
                               ['Bachelor', 3],
                               ['Master', 4],
                               ['PhD', 5],
                               ['MBA', 5]], 
                                columns = ['EduType', 'Mark'])
job_classifier = pd.DataFrame([['Unemployed', -5],
                               ['LowGrade', 1],
                               ['BlueCollar', 2],
                               ['Self-employed', 2],
                               ['WhiteCollar', 4],
                               ['MidMan', 5],
                               ['TopMan', 7]], 
                                columns = ['Job', 'Mark'])
experience_classifier = pd.DataFrame([[range(1), 0],
                                    [np.arange(0.25, 3.25, 0.25), 1],
                                    [range(4, 8), 2],
                                    [range(8, 16), 3],
                                    [range(16, 21), 4],
                                    [range(21, 100), 5]], 
                                    columns = ['Experience', 'Mark'])
income_classifier = pd.DataFrame([[range(10000, 30000, 1000), 1],
                                [range(30000, 50000, 1000), 2],
                                [range(50000, 80000, 1000), 3],
                                [range(80000, 300000, 1000), 4],
                                [range(300000, 500000, 1000), 5],
                                [range(500000, 1000000, 1000), 6],
                                [range(1000000, 3005000, 1000), 7]], 
                                columns = ['Income', 'Mark'])
ois_classifier = pd.DataFrame([[range(1), 0], #other income sources
                                [range(1000, 11000, 1000), 1],
                                [range(11000, 51000, 1000), 2],
                                [range(51000, 1000000, 1000), 3]], 
                                columns = ['OIS', 'Mark'])
brb_classifier = pd.DataFrame([[range(1), 3], #burden rate before
                                    [np.round(np.arange(0.05, 0.3, 0.05), 2), 2],
                                    [np.round(np.arange(0.3, 1.05, 0.05), 2), 1],
                                    [np.round(np.arange(1.05, 3.05, 0.05), 2), 0],
                                    [np.round(np.arange(3.05, 10, 0.05), 2), -3]], 
                                    columns = ['BRB', 'Mark'])
possessions_classifier = pd.DataFrame([['-', 0],
                                       ['Poor', 1],
                                       ['Middle', 2],
                                       ['Good', 3]], 
                                        columns = ['PosQuality', 'Mark'])
credithistory_classifier = pd.DataFrame([['-', 0],
                                       ['Poor', -3],
                                       ['Middle', 1],
                                       ['Good', 3]], 
                                        columns = ['CredHist', 'Mark'])
appsum_classifier = pd.DataFrame([[range(100, 1100, 100), 4],
                                [range(1100, 5100, 100), 3],
                                [range(5100, 50100, 100), 2],
                                [range(50100, 250100, 100), 1],
                                [range(250100, 500100, 100), 0]], columns = ['AppSum', 'Mark'])
duration_classifier = pd.DataFrame([[range(21, 64), 5],
                                    [range(64, 127), 4],
                                    [range(127, 169), 3],
                                    [range(169, 253), 2],
                                    [range(253, 505), 1]], 
                                    columns = ['Dur', 'Mark'])
bra_classifier = pd.DataFrame([[np.arange(0, 0.3, 0.1), 4],#burden rate after
                                [np.round(np.arange(0.3, 1.1, 0.1), 1), 3],
                                [np.round(np.arange(1.1, 3, 0.1), 1), 1],
                                [np.round(np.arange(3, 10, 0.1), 1), -3]], columns = ['BRA', 'Mark'])

In [12]:
loans = pd.DataFrame(columns=['IdApp', 'AppType', 'Sex', 'Age', 
                  'Education', 
                  'Job', 'Experience', 
                  'AnnualIncome', 'OtherSources', 
                  'BurdenRateBefore',
                  'Possessions', 
                  'CreditHistory', 
                  'AppSum', 'Duration',
                  'BurdenRateAfter', 
                  'CreditScore', 'ActualDefault'])

In [13]:
loans

Empty DataFrame
Columns: [IdApp, AppType, Sex, Age, Education, Job, Experience, AnnualIncome, OtherSources, BurdenRateBefore, Possessions, CreditHistory, AppSum, Duration, BurdenRateAfter, CreditScore, ActualDefault]
Index: []

In [14]:
for i in range(1000):
    idApp = i
    appType = random.choice(['Card', 'Consumer loan', 'Car loan', 'Mortgage', 
                             'SP loan'])
    sex = random.choice(['M', 'F'])
    age = random.choice(range(18, 66))
    if age <= 25:
        education = random.choice(['Secondary', 'High school', 'Sharaga', 
                                   'Bachelor', 'Master', 'PhD'])
    else:
        education = random.choice(['Secondary', 'High school', 'Sharaga', 
                                   'Bachelor', 'Master', 'PhD', 'MBA'])
    if age < 30:
        job = random.choice(['Unemployed', 'LowGrade', 'BlueCollar', 
                             'Self-employed', 'WhiteCollar', 'MidMan'])
        if job == 'Unemployed':
            annualIncome = random.choice(range(0, 16000, 2000))
        elif job in ['LowGrade', 'BlueCollar']:
            annualIncome = random.choice(range(10000, 90000, 2000))
        else:
            annualIncome = random.choice(range(20000, 300000, 10000)) #переделать в бета-распределение
    else:
        job = random.choice(['Unemployed', 'LowGrade', 'BlueCollar', 
                             'Self-employed', 'WhiteCollar', 'MidMan', 
                             'TopMan'])
        if job == 'Unemployed':
            annualIncome = random.choice(range(0, 20000, 2000))
        elif job in ['Self-employed', 'WhiteCollar', 'MidMan', 'TopMan']:
            annualIncome = random.choice(range(100000, 300000, 10000)) 
        else:
            annualIncome = random.choice(range(10000, 100000, 2000)) 
    experience = int((age - 18) * np.random.beta(6, 1))
    #annualIncome = random.choice(range(10000, 3000000, 10000))
    ois = random.choice(range(0, 70000, 10000)) #other income sources
    burdenRateBefore = random.choice([0, random.choice(range(0, 16))/4])
    possessions = random.choice(['-', 'Poor', 'Middle', 'Good'])
    creditHistory = random.choice(['-', 'Poor', 'Middle', 'Good'])
    appSum = random.choice(range(100, 500100, 100))
    duration = random.choice(range(21, 504, 21))
    try:
        burdenRateAfter = round(burdenRateBefore + appSum / (annualIncome + ois), 1)
    except:
        burdenRateAfter = 5 

    for cl in range(len(age_classifier)):
        if age in age_classifier.iloc[cl, 0]:
            age_score = age_classifier.iloc[cl, 1]
            break
    for cl in range(len(apptype_classifier)):
        if appType == apptype_classifier.iloc[cl, 0]:
            appType_score = apptype_classifier.iloc[cl, 1]
            break
    for cl in range(len(edu_classifier)):
        if education == edu_classifier.iloc[cl, 0]:
            edu_score = edu_classifier.iloc[cl, 1]
            break
    for cl in range(len(job_classifier)):
        if job == job_classifier.iloc[cl, 0]:
            job_score = job_classifier.iloc[cl, 1]
            break    
    for cl in range(len(experience_classifier)):
        if experience in experience_classifier.iloc[cl, 0]:
            experience_score = experience_classifier.iloc[cl, 1]
            break            
    for cl in range(len(income_classifier)):
        if annualIncome in income_classifier.iloc[cl, 0]:
            income_score = income_classifier.iloc[cl, 1]
            break    
    for cl in range(len(ois_classifier)):
        if ois in ois_classifier.iloc[cl, 0]:
            ois_score = ois_classifier.iloc[cl, 1]
            break 
    for cl in range(len(brb_classifier)):
        if burdenRateBefore in brb_classifier.iloc[cl, 0]:
            brb_score = brb_classifier.iloc[cl, 1]
            break 
    for cl in range(len(possessions_classifier)):
        if possessions == possessions_classifier.iloc[cl, 0]:
            possessions_score = possessions_classifier.iloc[cl, 1]
            break
    for cl in range(len(credithistory_classifier)):
        if creditHistory == credithistory_classifier.iloc[cl, 0]:
            ch_score = credithistory_classifier.iloc[cl, 1]
            break
    for cl in range(len(appsum_classifier)):
        if appSum in appsum_classifier.iloc[cl, 0]:
            appSum_score = appsum_classifier.iloc[cl, 1]
            break    
    for cl in range(len(duration_classifier)):
        if duration in duration_classifier.iloc[cl, 0]:
            dur_score = duration_classifier.iloc[cl, 1]
            break 
    for cl in range(len(bra_classifier)):
        if burdenRateAfter in bra_classifier.iloc[cl, 0]:
            bra_score = bra_classifier.iloc[cl, 1]
            break 
    #Дальше запихать расчёт
    #creditScore = random.choice(range(-10, 101, 10))
    creditScore = sum([age_score, appType_score, edu_score,
                       job_score, experience_score, income_score,
                       ois_score, brb_score, possessions_score,
                       ch_score, appSum_score, dur_score, bra_score])
    '''
    prob_d = round(1 - np.random.beta(1, 7) / 10 + 0.01, 2)
    default_prob = random.choice(range(1, 101))/100 * (20 / creditScore) * np.exp(1)
    '''
    
    if creditScore <= 18:
        default_event = 1
    else:
        default_event = 0
    
    
    loans.loc[i] = {'IdApp':idApp, 'AppType':appType, 'Sex':sex, 'Age':age, 
                  'Education':education, 
                  'Job':job, 'Experience':experience, 
                  'AnnualIncome':annualIncome, 'OtherSources':ois, 
                  'BurdenRateBefore':burdenRateBefore,
                  'Possessions':possessions, 
                  'CreditHistory':creditHistory, 
                  'AppSum':appSum, 'Duration':duration,
                  'BurdenRateAfter':burdenRateAfter, 
                  'CreditScore':creditScore,
                   'ActualDefault':default_event}

In [15]:
loans

,IdApp,AppType,Sex,Age,Education,Job,Experience,AnnualIncome,OtherSources,BurdenRateBefore,Possessions,CreditHistory,AppSum,Duration,BurdenRateAfter,CreditScore,ActualDefault
0,0,Consumer loan,F,42,High school,Self-employed,12,270000,20000,0,Middle,-,34200,252,0.1,31,0
1,1,Card,F,46,MBA,Unemployed,23,8000,10000,1.75,Good,Middle,418900,336,25.0,23,0
2,2,SP loan,M,61,High school,LowGrade,37,90000,0,0,-,Good,187900,210,2.1,24,0
3,3,Car loan,F,26,Bachelor,Unemployed,5,6000,20000,0,Poor,Middle,164500,126,6.3,19,0
4,4,Car loan,M,62,Secondary,TopMan,40,230000,10000,0.75,-,Middle,419900,168,2.5,27,0
5,5,Card,M,23,High school,MidMan,4,200000,40000,1.25,Middle,Middle,368100,105,2.8,25,0
6,6,Card,M,23,Bachelor,Self-employed,4,60000,30000,0,-,Middle,218000,210,2.4,23,0
7,7,Consumer loan,M,37,PhD,Self-employed,13,250000,40000,0,Good,Middle,223900,21,0.8,38,0
8,8,Mortgage,F,18,Secondary,WhiteCollar,0,280000,0,1.5,Middle,-,440700,294,3.1,13,1
9,9,Consumer loan,M,56,PhD,LowGrade,36,66000,10000,0,Poor,Middle,163800,105,2.2,29,0
10,10,Car loan,M,58,High school,MidMan,35,260000,10000,0,-,-,185600,126,0.7,31,0
11,11,Card,M,45,Master,TopMan,20,290000,50000,1.25,Good,Middle,111000,399,1.6,33,0
12,12,Card,F,36,Sharaga,LowGrade,10,10000,60000,0,Middle,Middle,345100,315,4.9,19,0
13,13,Card,F,38,Secondary,WhiteCollar,18,260000,60000,0,Poor,Middle,274500,378,0.9,29,0
14,14,Car loan,F,18,Master,Self-employed,0,100000,10000,0,Poor,Middle,165700,231,1.5,24,0
15,15,Mortgage,F,47,Bachelor,WhiteCollar,25,120000,40000,0,-,-,12300,441,0.1,35,0
16,16,SP loan,M,27,Bachelor,WhiteCollar,7,180000,40000,1.25,Good,Middle,179700,210,2.1,28,0
17,17,Consumer loan,F,55,Sharaga,LowGrade,36,96000,0,2.5,-,Middle,104300,147,3.6,19,0
18,18,Car loan,M,35,High school,Unemployed,15,4000,60000,2.75,-,Good,271800,231,7.0,15,1
19,19,Car loan,M,23,Bachelor,Self-employed,4,140000,60000,0,-,Poor,390600,105,2.0,24,0
20,20,Consumer loan,F,43,Secondary,WhiteCollar,23,190000,30000,0,Middle,-,446700,294,2.0,28,0
21,21,Mortgage,F,31,Bachelor,TopMan,12,230000,60000,0,Poor,Good,474400,378,1.6,37,0
22,22,SP loan,M,56,Secondary,TopMan,22,250000,50000,2,Poor,Middle,373600,420,3.2,21,0
23,23,Mortgage,F,21,Master,BlueCollar,2,52000,20000,3,Good,Good,117100,399,4.6,22,0
24,24,Mortgage,F,25,Secondary,WhiteCollar,6,30000,0,3.75,Poor,-,426400,294,18.0,10,1
25,25,Consumer loan,M,26,High school,Self-employed,7,90000,0,0,Good,Middle,273000,252,3.0,20,0
26,26,Car loan,M,27,PhD,Self-employed,8,90000,50000,0,Middle,Middle,43700,378,0.3,34,0
27,27,Car loan,M,47,PhD,BlueCollar,27,70000,0,2.25,-,Poor,254800,399,5.9,16,1
28,28,Car loan,M,55,MBA,LowGrade,27,34000,30000,0,Middle,Middle,387500,210,6.1,26,0
29,29,Mortgage,M,54,MBA,TopMan,31,180000,0,3,Poor,Good,367700,63,5.0,34,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,970,Consumer loan,F,44,MBA,WhiteCollar,23,290000,10000,0,-,Middle,339900,147,1.1,33,0
971,971,Mortgage,F,34,MBA,TopMan,14,160000,60000,3.75,Middle,Middle,293100,483,5.1,28,0
972,972,Card,F,30,PhD,TopMan,10,180000,60000,2.5,Good,-,159200,210,3.2,29,0
973,973,Car loan,F,23,PhD,BlueCollar,4,82000,40000,0.25,Good,Poor,238300,441,2.2,25,0
974,974,Consumer loan,M,28,Sharaga,WhiteCollar,7,20000,40000,0,Middle,Good,216000,378,3.6,23,0
975,975,SP loan,F,56,MBA,Unemployed,33,0,0,3.75,-,-,143900,357,5.0,5,1
976,976,Car loan,F,29,High school,WhiteCollar,7,110000,30000,0,Poor,Good,393600,42,2.8,32,0
977,977,SP loan,M,48,Bachelor,WhiteCollar,26,110000,30000,2.75,Poor,Poor,398700,189,5.6,20,0
978,978,SP loan,M,61,Secondary,BlueCollar,37,24000,50000,2,Poor,-,271000,315,5.7,12,1
979,979,SP loan,M,57,Sharaga,Unemployed,33,6000,10000,3.75,Middle,Middle,305700,315,22.9,5,1
980,980,Mortgage,F,49,High school,WhiteCollar,27,280000,40000,0,Good,Good,445700,483,1.4,34,0
981,981,Card,F,25,High school,WhiteCollar,6,230000,30000,0,Middle,Middle,357600,168,1.4,26,0
982,982,Mortgage,F,35,Secondary,Unemployed,15,10000,0,0,Poor,-,5700,231,0.6,18,1
983,983,SP loan,M,35,Secondary,WhiteCollar,16,190000,40000,0,-,Good,427400,231,1.9,29,0
984,984,Consumer loan,F,49,High school,TopMan,23,160000,10000,0,Middle,Poor,226300,147,1.3,30,0
985,985,Consumer loan,M,51,Bachelor,Self-employed,32,210000,10000,0,Middle,Poor,140200,84,0.6,30,0
986,986,Consumer loan,M,19,Secondary,Unemployed,0,10000,30000,0,-,Good,444000,84,11.1,14,1
987,987,Consumer loan,F,23,Bachelor,Self-employed,4,40000,50000,0,Middle,Good,170000,84,1.9,29,0
988,988,Card,M,58,MBA,MidMan,39,200000,40000,3,Poor,Poor,224500,189,3.9,21,0
989,989,Consumer loan,M,26,High school,BlueCollar,7,28000,10000,0,Poor,Poor,192300,336,5.1,12,1
990,990,Car loan,F,31,High school,TopMan,9,190000,0,2.75,-,Middle,384700,42,4.8,25,0
991,991,Mortgage,F,36,MBA,TopMan,16,110000,30000,3,Good,-,153200,147,4.1,34,0
992,992,Mortgage,F,49,Master,BlueCollar,25,46000,20000,0.25,Middle,Poor,421200,462,6.6,21,0
993,993,Car loan,F,63,Sharaga,TopMan,44,240000,30000,0.5,Poor,-,12600,441,0.5,32,0
994,994,Card,F,20,Bachelor,LowGrade,1,58000,30000,0,Good,Middle,380700,189,4.3,18,1
995,995,Car loan,F,41,Secondary,TopMan,18,140000,30000,2,Good,Good,245200,483,3.4,29,0
996,996,Consumer loan,M,22,Sharaga,BlueCollar,3,72000,30000,0.25,Poor,Middle,113500,483,1.4,21,0
997,997,SP loan,M,36,Sharaga,TopMan,17,200000,40000,0,Middle,Poor,208200,273,0.9,32,0
998,998,Car loan,F,46,MBA,BlueCollar,26,80000,60000,2.5,Middle,Good,462000,168,5.8,30,0
999,999,Mortgage,F,52,Sharaga,MidMan,32,180000,50000,1.25,Poor,-,341500,84,2.7,31,0